version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: occupation-tracker-backend:1.0
    container_name: occupation-tracker-postgres-backend
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    command: ["/app/wait-for-it.sh", "postgres:5432", "--", "java", "-jar", "/app/webshop-0.0.1-SNAPSHOT.jar"]

  frontend:
    build:
      context: ./frontend/webshopapp
      dockerfile: Dockerfile
    image: occupation-tracker-frontend:1.0
    container_name: occupation-tracker-postgres-frontend
    ports:
      - "4200:4200"

  postgres:
    image: postgres:latest
    container_name: occupation-tracker
    environment:
      POSTGRES_PASSWORD: 3110
      POSTGRES_USER: postgres
      POSTGRES_DB: master
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 4318:4318
      - 16686:16686
    environment:
      - COLLECTOR_OTLP_ENABLED=true
